project:
  type: website

website:
  site-url: https://berkeley-stat244.github.io/spring-2025
  sidebar:
    style: docked
    title: "Stat 244"
    logo: assets/stat_bear.png
    logo-alt: "UC Berkeley Statistics logo"
    tools:
      - icon: github
        href: https://github.com/berkeley-stat244/spring-2025
        aria-label: GitHub
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: office_hours.qmd
        text: Office Hours
      - section: "Course Notes"
        contents:
          - href: notes/notes1.qmd
          - href: notes/notes2.qmd
      - section: "Problem Sets"
        contents:
          - href: ps/ps1.qmd
          - href: ps/ps2.qmd
          - href: ps/ps3.qmd
      - section: "How tos"
        contents:
          - href: howtos/accessJulia.md
          - href: howtos/accessSCF.md
          - href: howtos/useQuarto.qmd
          - href: howtos/installPython.md
          - href: howtos/installGit.md
      - href: license.qmd
        text: License
          
format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true

execute:
  freeze: auto

